### ISSUE TITLE
Learning Objective Suggestions

### ISSUE THREAD

**Issue by ibirnam** [Make-School-Courses/MOB-1.3-Dynamic-iOS-Apps#1]
**Suggestions for adjusting Learning Objectives, let me know if you want to discuss.**

Rename "Learning Objectives and Competencies" to just "Learning Objectives"

Students by the end of the course will be able to ...

1. ~Understand and use closures~ Explain and use closures
2. Use callbacks and delegation to pass information between views/objects
3. Identify and use the target-action communication pattern in UIKit code
4. Identify and use NSNotification in transferring information in an iOS app
5. ~Understand how memory management works in Swift~ Explain how memory management works in Swift
6. ~Interact with public APIs with or without authentication~ Use public APIs with or without authentication
7. ~Make a network request in iOS using a networking layer~ Demonstrate how to make a network request in iOS using a networking layer
8. Parse a JSON network response using native Swift tools

**Comment by amelinagzz** [comment]
Thanks, done 👍🏼
